# Site settings
name: 公会驻地
email: feiliyaailiya1@icloud.com
author: anchoriteFili
url: http://www.anchoritefili.com
resume_site: https://anchoritefili.github.io
github: https://github.com/anchoriteFili/
baseurl: ""
description: hahaha
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

